export default [
  {
    id: 1,
    name: 'folder1',
    chosen: false,
    enabled: true,
    type: 'folder',
    level: 0,
    parent: 0,
  },
  {
    id: 2,
    name: 'folder2',
    chosen: false,
    enabled: false,
    type: 'folder',
    level: 0,
    parent: 0,
  },
  {
    id: 3,
    name: 'folder3',
    chosen: false,
    enabled: true,
    type: 'folder',
    level: 0,
    parent: 0,
  },
  {
    id: 4,
    name: 'file1.csv',
    ext: 'csv',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 0,
    parent: 0,
  },
  {
    id: 5,
    name: 'file2.jpg',
    ext: 'jpg',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 0,
    parent: 0,
  },
  {
    id: 6,
    name: 'file3.png',
    ext: 'png',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 0,
    parent: 0,
  },
  {
    id: 7,
    name: 'file4.csv',
    ext: 'csv',
    chosen: false,
    enabled: false,
    type: 'file',
    level: 0,
    parent: 0,
  },
  {
    id: 8,
    name: 'file5.csv',
    ext: 'csv',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 1,
    parent: 1,
  },
  {
    id: 9,
    name: 'file6.csv',
    ext: 'csv',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 1,
    parent: 1,
  },
  {
    id: 10,
    name: 'file7.ppt',
    ext: 'ppt',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 1,
    parent: 1,
  },
  {
    id: 11,
    name: 'folder4',
    chosen: false,
    enabled: true,
    type: 'folder',
    level: 1,
    parent: 1,
  },
  {
    id: 12,
    name: 'folder5',
    chosen: false,
    enabled: true,
    type: 'folder',
    level: 1,
    parent: 1,
  },
  {
    id: 13,
    name: 'folder6',
    chosen: false,
    enabled: true,
    type: 'folder',
    level: 1,
    parent: 1,
  },
  {
    id: 14,
    name: 'folder7',
    chosen: false,
    enabled: true,
    type: 'folder',
    level: 1,
    parent: 2,
  },
  {
    id: 15,
    name: 'folder8',
    chosen: false,
    enabled: true,
    type: 'folder',
    level: 1,
    parent: 2,
  },
  {
    id: 16,
    name: 'file1',
    ext: '',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 1,
    parent: 2,
  },
  {
    id: 17,
    name: 'file4',
    ext: '',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 1,
    parent: 2,
  },
  {
    id: 18,
    name: 'file12.ppt',
    ext: 'ppt',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 2,
    parent: 11,
  },
  {
    id: 19,
    name: 'file4',
    ext: '',
    chosen: false,
    enabled: true,
    type: 'file',
    level: 2,
    parent: 11,
  },
];
